site:
    title:        Michael COULLERET
    description:
    author_name:  Michael COULLERET
    author_email: michael@coulleret.pro
    author_url:   https://www.coulleret.pro
    url_absolute: https://20uf.github.io

engine:
    themes:
        - %dir%/vendor/carew/theme-bootstrap
